from playwright.sync_api import sync_playwright
playwright = sync_playwright().start()
browser = playwright.firefox.launch(headless=False, slow_mo=1000)
page = browser.new_page()
page.goto('https://autbor.com/example3.html')
page.locator('#login_user').fill('your_real_username_here')
page.locator('#login_pass').fill('your_real_password_here')
page.locator('input[type=submit]').click()
browser.close()
playwright.stop()